<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9">
    <xsl:output method="html" encoding="UTF-8" indent="yes"/>
    <xsl:template match="/">
        <html lang="en">
            <head>
                <title>XML Sitemap | Sortiq Solutions</title>
                <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
                <style>
                    body {
                        font-family: 'Nunito', 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
                        color: #1a2238;
                        background-color: #f7f9fc;
                        margin: 0;
                        padding: 30px 15px;
                    }
                    .container {
                        max-width: 960px;
                        margin: 0 auto;
                        background: #ffffff;
                        padding: 30px;
                        border-radius: 12px;
                        box-shadow: 0 4px 12px rgba(0, 23, 62, 0.05);
                    }
                    .header {
                        border-bottom: 2px solid #f1f3f7;
                        padding-bottom: 20px;
                        margin-bottom: 24px;
                    }
                    h1 {
                        color: #00173e;
                        font-size: 28px;
                        margin: 0 0 8px 0;
                        font-weight: 700;
                    }
                    p {
                        color: #626f8a;
                        margin: 0;
                        font-size: 15px;
                        line-height: 1.6;
                    }
                    .meta-info {
                        display: flex;
                        gap: 20px;
                        margin-top: 12px;
                        font-size: 13px;
                        font-weight: 600;
                    }
                    .meta-info span {
                        color: #ff5a00;
                        background: rgba(255, 90, 0, 0.08);
                        padding: 4px 10px;
                        border-radius: 4px;
                    }
                    table {
                        width: 100%;
                        border-collapse: collapse;
                        margin-top: 15px;
                    }
                    th {
                        background-color: #00173e;
                        color: #ffffff;
                        text-align: left;
                        padding: 12px 16px;
                        font-size: 14px;
                        font-weight: 600;
                        letter-spacing: 0.5px;
                    }
                    th:first-child {
                        border-top-left-radius: 6px;
                    }
                    th:last-child {
                        border-top-right-radius: 6px;
                    }
                    td {
                        padding: 12px 16px;
                        border-bottom: 1px solid #eef2f6;
                        font-size: 14px;
                        word-break: break-all;
                    }
                    tr:hover td {
                        background-color: #fcfdfe;
                    }
                    tr:last-child td {
                        border-bottom: none;
                    }
                    a {
                        color: #005eff;
                        text-decoration: none;
                        font-weight: 500;
                    }
                    a:hover {
                        text-decoration: underline;
                        color: #ff5a00;
                    }
                    .date-text {
                        color: #626f8a;
                    }
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="header">
                        <h1>XML Sitemap</h1>
                        <p>This dynamic XML Sitemap is generated by Sortiq Solutions for search engines to discover and crawl our website pages effectively.</p>
                        <div class="meta-info">
                            <span>Total URLs: <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></span>
                        </div>
                    </div>
                    
                    <table>
                        <thead>
                            <tr>
                                <th style="width: 50%;">URL</th>
                                <th style="width: 15%;">Change Freq</th>
                                <th style="width: 10%;">Priority</th>
                                <th style="width: 25%;">Last Modified</th>
                            </tr>
                        </thead>
                        <tbody>
                            <xsl:for-each select="sitemap:urlset/sitemap:url">
                                <tr>
                                    <td>
                                        <a href="{sitemap:loc}">
                                            <xsl:value-of select="sitemap:loc"/>
                                        </a>
                                    </td>
                                    <td style="text-transform: capitalize; color: #626f8a; font-weight: 500;">
                                        <xsl:value-of select="sitemap:changefreq"/>
                                    </td>
                                    <td>
                                        <span style="font-weight: 600; color: #1a2238;">
                                            <xsl:value-of select="sitemap:priority"/>
                                        </span>
                                    </td>
                                    <td>
                                        <span class="date-text">
                                            <xsl:choose>
                                                <xsl:when test="sitemap:lastmod">
                                                    <xsl:value-of select="substring(sitemap:lastmod, 0, 11)"/>
                                                    <xsl:text> </xsl:text>
                                                    <xsl:value-of select="substring(sitemap:lastmod, 12, 8)"/>
                                                </xsl:when>
                                                <xsl:otherwise>
                                                    -
                                                </xsl:otherwise>
                                            </xsl:choose>
                                        </span>
                                    </td>
                                </tr>
                            </xsl:for-each>
                        </tbody>
                    </table>
                </div>
            </body>
        </html>
    </xsl:template>
</xsl:stylesheet>
