<?php

return [
    'pages' => [
        'about' => 'frontend.pages.about',
        'clients' => 'frontend.clients.clients-page',
        'why-us' => 'frontend.pages.why-us',
        'careers' => 'frontend.pages.careers',
        'expertise' => 'frontend.pages.expertise',
        'videos' => 'frontend.videos.videos-page',
        'contact' => 'frontend.pages.contact',
        'reviews' => 'frontend.reviews.reviews-page',
        'portfolio' => 'frontend.portfolio.portfolio-page',
        'cases' => 'frontend.pages.case-studies',
        'internship' => 'frontend.pages.internship',
        'terms' => 'frontend.pages.terms',
        'faq' => 'frontend.pages.faq',
        'support' => 'frontend.pages.support',
    ],

    'services' => [
        'web',
        'design',
        'laravel',
        'wordpress',
        'ecommerce',
        'marketing',
        'seo',
        'smo',
        'graphics',
        'banners',
        'logos',
        'maintenance',
        'bigcommerce',
        'mern',
        'apps',
        'testing',
        'security',
        'hubspot',
        'zoho',
        'php',
        'codeigniter',
        'shopify',
        'react',
        'node',
        'vue',
    ],

    'legacy_pages' => [
        'about-us' => 'about',
        'why-choose-us' => 'why-us',
        'our-career' => 'careers',
        'our-expertise' => 'expertise',
        'portfolios' => 'portfolio',
        'case-studies' => 'cases',
    ],

    'legacy_blogs' => [
        'the-importance-of-ui-ux-design-in-modern-web-development' => 'ui-ux-design',
        'top-mistakes-businesses-make-while-developing-a-website' => 'website-mistakes',
        'why-website-security-matters-for-your-business-growth' => 'website-security',
        'top-it-company-in-chandigarh-transforming-your-digital-presence' => 'digital-presence',
        'why-sortiq-solutions-is-the-best-it-company-in-mohali-for-2026' => 'mohali-it-company',
        'how-to-choose-the-right-ecommerce-development-company-for-your-business' => 'ecommerce-company',
        'best-seo-company-in-chandigarh-for-business-growth' => 'seo-company',
        'growth-focused-web-development-company-in-chandigarh' => 'web-growth',
        'top-it-company-in-chandigarh-choosing-the-right-partner-for-your-business' => 'it-partner',
        'role-of-business-analyst-in-modern-it-organizations' => 'business-analyst',
        'top-reasons-why-cloud-computing-is-essential-for-modern-businesses' => 'cloud-computing',
        'why-wix-is-the-best-website-builder-for-modern-businesses' => 'wix-builder',
        'why-choose-mern-stack-for-modern-web-apps' => 'mern-web-apps',
        'why-shopify-is-the-best-e-commerce-platform-for-your-business' => 'shopify-platform',
        'cybersecurity-why-it-matters-more-than-ever' => 'cybersecurity',
        'how-networking-powers-the-modern-world-behind-the-scenes-of-connectivity' => 'networking',
        'java-programming-the-ultimate-guide-for-beginners-and-professionals' => 'java-guide',
        'what-is-node-js-a-complete-guide-for-beginners' => 'nodejs-guide',
        'top-reasons-why-wordpress-is-the-best-cms-for-your-website' => 'wordpress-cms',
        'the-strategic-role-of-cloud-computing-in-it-transformation' => 'cloud-it',
        '6-innovative-strategies-to-boost-your-local-business-presence' => 'local-business',
        'how-chatbots-are-revolutionizing-ecommerce-conversions' => 'chatbots-ecommerce',
        'how-to-design-a-stunning-and-engaging-website-that-stands-out' => 'website-design',
        'the-ultimate-shopify-seo-checklist-to-rank-your-site-faster' => 'shopify-seo',
        'the-ultimate-guide-to-branding-building-a-strong-identity-for-your-business' => 'branding-guide',
        'the-ultimate-guide-to-seo-boost-your-websites-visibility' => 'seo-guide',
        'the-ultimate-guide-to-digital-marketing-in-2025' => 'digital-marketing',
        'the-comprehensive-guide-to-modern-software-development' => 'software-development',
        'the-future-of-ai-how-artificial-intelligence-is-reshaping-our-world' => 'future-of-ai',
        'innovation-unleashed-the-power-of-technology-in-shaping-our-future' => 'technology-future',
        'how-to-build-a-successful-e-commerce-website-on-wix' => 'ecommerce-wix',
        'why-the-mern-stack-is-a-game-changer-for-web-development' => 'mern-web-dev',
        'the-importance-of-cybersecurity-in-modern-business' => 'business-cybersecurity',
        'why-cloud-hosting-is-revolutionizing-web-solutions' => 'cloud-hosting',
        'the-future-of-e-commerce-why-its-all-about-custom-solutions' => 'custom-ecommerce',
        'best-domain-name-for-business' => 'domain-name',
    ],

    'legacy_services' => [
        'web-development' => 'web',
        'web-design' => 'design',
        'laravel-development' => 'laravel',
        'wordpress-development' => 'wordpress',
        'ecommerce-development' => 'ecommerce',
        'digital-marketing' => 'marketing',
        'graphic-design' => 'graphics',
        'banner-design' => 'banners',
        'logo-design' => 'logos',
        'website-maintenance' => 'maintenance',
        'bigcommerce-development' => 'bigcommerce',
        'mern-stack-development' => 'mern',
        'app-development' => 'apps',
        'software-testing' => 'testing',
        'cyber-security' => 'security',
        'hubspot-crm' => 'hubspot',
        'zoho-crm' => 'zoho',
        'php-development' => 'php',
        'codeigniter-development' => 'codeigniter',
        'shopify-development' => 'shopify',
        'react-development' => 'react',
        'node-development' => 'node',
        'vue-development' => 'vue',
    ],
];
